
export const styles = {
  container: {
    display: "flex",
    flexDirection: "column" as const,
    height: "100vh",
    overflow: "hidden",
  },
  topScroll: {
    height: "30px",
    overflowX: "auto" as const,
    whiteSpace: "nowrap" as const,
    borderBottom: "1px solid #ccc",
    background: "#fafafa",
    flexShrink: 0,
  },
  scrollRow: { display: "flex", height: "100%" },
  testBox: {
    display: "flex",
    alignItems: "center",
    borderRight: "1px solid #ccc",
    padding: "0 5px",
    background: "#fff",
    cursor: "pointer",
  },
  popup: {
    background: "#fff",
    border: "1px solid #ccc",
    borderRadius: "4px",
    minWidth: "200px",
    maxHeight: "300px",
    overflowY: "auto" as const,
    boxShadow: "0 4px 12px rgba(0,0,0,0.2)",
    zIndex: 2000,
  },
  popupContent: { padding: "5px" },
  dropdownItem: {
    padding: "5px",
    cursor: "pointer",
    borderBottom: "1px solid #eee",
  },
  toggleItem: {
    display: "flex",
    alignItems: "center",
    padding: "5px",
    borderBottom: "1px solid #eee",
    cursor: "pointer",
  },
  mainArea: { display: "flex", flex: 1, overflow: "hidden" },
  leftColumn: {
    width: "40px",
    flexShrink: 0,
    borderRight: "1px solid #ccc",
    background: "#fafafa",
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    justifyContent: "flex-start" as const,
  },
  numberBox: {
    height: "40px",
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderBottom: "1px solid #ccc",
    cursor: "pointer",
  },
  submenu: {
    position: "absolute" as const,
    left: "40px",
    top: "70px",
    width: "180px",
    backgroundColor: "#f0f0f0",
    border: "1px solid #ccc",
    padding: "10px",
    boxSizing: "border-box" as const,
    zIndex: 1000,
    maxHeight: "calc(100vh - 70px)",
    overflowY: "auto" as const,
  },
  submenuItem: {
    display: "flex",
    alignItems: "center",
    padding: "8px",
    cursor: "pointer",
    borderBottom: "1px solid #ddd",
    backgroundColor: "#fff",
    "&:hover": {
      backgroundColor: "#f5f5f5",
    },
  },
  submenuText: {
    marginLeft: "8px",
    fontSize: "14px",
  },
  fibSubmenu: {
    position: "absolute" as const,
    left: "40px",
    top: "110px",
    width: "220px",
    backgroundColor: "#f0f0f0",
    border: "1px solid #ccc",
    padding: "10px",
    boxSizing: "border-box" as const,
    zIndex: 1000,
    maxHeight: "calc(100vh - 110px)",
    overflowY: "auto" as const,
  },
  patternSubmenu: {
    position: "absolute" as const,
    left: "40px",
    top: "150px",
    width: "200px",
    backgroundColor: "#f0f0f0",
    border: "1px solid #ccc",
    padding: "10px",
    boxSizing: "border-box" as const,
    zIndex: 1000,
    maxHeight: "calc(100vh - 150px)",
    overflowY: "auto" as const,
  },
  projectionSubmenu: {
    position: "absolute" as const,
    left: "40px",
    top: "190px",
    width: "220px",
    backgroundColor: "#f0f0f0",
    border: "1px solid #ccc",
    padding: "10px",
    boxSizing: "border-box" as const,
    zIndex: 1000,
    maxHeight: "calc(100vh - 190px)",
    overflowY: "auto" as const,
  },
  brushesSubmenu: {
    position: "absolute" as const,
    left: "40px",
    top: "230px",
    width: "200px",
    backgroundColor: "#f0f0f0",
    border: "1px solid #ccc",
    padding: "10px",
    boxSizing: "border-box" as const,
    zIndex: 1000,
    maxHeight: "calc(100vh - 230px)",
    overflowY: "auto" as const,
  },
  submenuSectionHeader: {
    padding: "8px 0",
    fontSize: "12px",
    color: "#555",
    fontWeight: "bold",
    borderBottom: "1px solid #ddd",
    marginBottom: "5px",
  },
  mainChart: {
    flex: 1,
    background: "#f9f9f9",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
};
